In [44]:
import pandas as pd

## feature.binary.csv

In [81]:
features = pd.read_csv('./feature.binary.csv')
#features = features.set_index('Name')
features

,Name,10004236570487500000,1.00063E+19,1.00092E+18,10010614138931100000,1.00135E+19,10025880196521300000,1.00261E+19,1.0037E+19,1.00394E+19,...,9.98281E+18,9.9853E+17,9.98839E+18,9.99038E+18,9.99128E+18,9.99237E+16,9.99579E+18,9.9964E+18,9.99682E+18,9.99869E+18
0,a1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,a2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,a3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,a4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,a6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,a123,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
96,a124,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
97,a125,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98,a126,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99,a128,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [82]:
features.shape

(100, 5577)

In [83]:
list(filter(lambda x: x == 1, features.iloc[2]))

[1, 1, 1, 1, 1, 1, 1]

## Jiang1823Train.csv

In [84]:
labels = pd.read_csv('./Jiang1823Train.csv')
print(f"Labels shape: {labels.shape}")
labels

Labels shape: (1458, 2)

       Name Toxicity
0        a1        P
1        a2        P
2        a3        P
3        a4        P
4        a6        P
...     ...      ...
1453  a1819        N
1454  a1820        N
1455  a1821        N
1456  a1822        N
1457  a1823        N

[1458 rows x 2 columns]

In [85]:
labels['label'] = labels['Toxicity'].apply(lambda x: 1 if x == 'P' else 0)
labels = labels.drop(['Toxicity'], axis=1)
labels

       Name  labels
0        a1       1
1        a2       1
2        a3       1
3        a4       1
4        a6       1
...     ...     ...
1453  a1819       0
1454  a1820       0
1455  a1821       0
1456  a1822       0
1457  a1823       0

[1458 rows x 2 columns]

In [91]:
a = features.set_index('Name').join(labels.set_index('Name'), how='inner')
a

,10004236570487500000,1.00063E+19,1.00092E+18,10010614138931100000,1.00135E+19,10025880196521300000,1.00261E+19,1.0037E+19,1.00394E+19,1.00414E+19,...,9.9853E+17,9.98839E+18,9.99038E+18,9.99128E+18,9.99237E+16,9.99579E+18,9.9964E+18,9.99682E+18,9.99869E+18,labels
Name,,,,,,,,,,,,,,,,,,,,,
a1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
a2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
a3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
a4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
a6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
a123,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
a124,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
a125,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
a126,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
a128,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1

In [97]:
a.iloc[99].to_list()

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 ...]

## test.csv

In [ ]:
origin_features = pd.read_csv('./test.csv', header=None)
origin_features

In [ ]:
origin_feature.shape

In [ ]:
!jupyter nbconvert --to html eda.ipynb

In [ ]:
import torch

In [ ]:
a = torch.tensor([1.1,2.1,3.2])
a

In [ ]:
a = torch.tensor([1, 2, 3.], requires_grad=True)
print(a.grad)
out = a.sigmoid()
print(out)


c = out.data
print(c)
c.zero_() #使用in place函数对其进行修改

#会发现c的修改同时也会影响out的值
print(c)
print(out)

#这里的不同在于.data的修改不会被autograd追踪，这样当进行backward()时它不会报错，回得到一个错误的backward值
out.sum().backward()
print(a.grad)

In [ ]:
a = torch.tensor([1, 2, 3.], requires_grad=True)
a

In [ ]:
print(a.grad)

In [ ]:
out = a.sigmoid()
out

In [ ]:
c = out.data
c

In [ ]:
c.zero_()

In [ ]:
out

In [ ]:
out.sum()